python ./ASTARRodaje.py ./ASTAR-tests/map1.csv 1
python ./ASTARRodaje.py ./ASTAR-tests/map1.csv 2
python ./ASTARRodaje.py ./ASTAR-tests/map1.csv 3
python ./ASTARRodaje.py ./ASTAR-tests/map2.csv 1
python ./ASTARRodaje.py ./ASTAR-tests/map2.csv 2
python ./ASTARRodaje.py ./ASTAR-tests/map2.csv 3
python ./ASTARRodaje.py ./ASTAR-tests/map3.csv 1
python ./ASTARRodaje.py ./ASTAR-tests/map3.csv 2
python ./ASTARRodaje.py ./ASTAR-tests/map3.csv 3
python ./ASTARRodaje.py ./ASTAR-tests/map4.csv 1
python ./ASTARRodaje.py ./ASTAR-tests/map4.csv 2
python ./ASTARRodaje.py ./ASTAR-tests/map4.csv 3
python ./ASTARRodaje.py ./ASTAR-tests/map5.csv 1
python ./ASTARRodaje.py ./ASTAR-tests/map5.csv 2
python ./ASTARRodaje.py ./ASTAR-tests/map5.csv 3
python ./ASTARRodaje.py ./ASTAR-tests/map6.csv 1
python ./ASTARRodaje.py ./ASTAR-tests/map6.csv 2
python ./ASTARRodaje.py ./ASTAR-tests/map6.csv 3
python ./ASTARRodaje.py ./ASTAR-tests/map7.csv 1
python ./ASTARRodaje.py ./ASTAR-tests/map7.csv 2
python ./ASTARRodaje.py ./ASTAR-tests/map7.csv 3
python ./ASTARRodaje.py ./ASTAR-tests/map8.csv 1
python ./ASTARRodaje.py ./ASTAR-tests/map8.csv 2
python ./ASTARRodaje.py ./ASTAR-tests/map8.csv 3
